version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cuisine

  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - cuisine
    volumes:
      - .:/app/

volumes:
    postgres:

networks:
    cuisine:
        driver: bridge